packages:
  - 'apps/*'
  - 'apps/services/*'
  - 'apps/front-end/*'
  - 'libs/shared/*'
  - 'front-end/*'
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@swc/core'
  - 'nx'
